name: example
description: "context_plus example"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  context_plus: ^4.1.3
  async_listenable: ^1.2.0
  rxdart: ^0.28.0
  syntax_highlight: ^0.4.0
  dolumns: ^2.0.1
  url_router: ^0.2.1+1
  linked_scroll_controller: ^0.2.0
  performance: ^0.1.1
  highlight_text: ^1.8.0
  rive: ^0.13.17
  visibility_detector: ^0.4.0+2
  gap: ^3.0.1
  flutter_svg: ^2.0.14
  yaml: ^3.1.2
  indent: ^2.0.0
  web: ^1.1.0

  # Signals
  signals_flutter: ^5.5.1
  context_watch_signals: ^3.0.3

  # MobX
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1
  context_watch_mobx: ^3.0.2

  # Beacon
  state_beacon: ^0.14.6
  context_watch_beacon: ^1.0.0-dev.2

  # Bloc
  flutter_bloc: ^8.1.6
  context_watch_bloc: ^3.0.2

  # GetX
  get: ^5.0.0-release-candidate-9.2.1
  context_watch_getx: ^4.0.0-rc.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/showcase/
    - assets/svg/
    - lib/examples/showcase/variants/
    - lib/examples/animation_controller/variants/
    - lib/examples/rainbow/variants/
    - lib/examples/derived_state/variants/
    - lib/examples/counter/variants/
    - lib/examples/counter_with_propagation/variants/
    - lib/examples/nested_scopes/variants/
    - lib/examples/country_search/variants/
    - lib/examples/country_search/util/countries.json
    - pubspec.yaml
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode.ttf
