name: example
description: "context_plus example"
publish_to: "none"
version: 1.0.0

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  context_plus: ^4.0.0
  async_listenable: ^1.0.1
  rxdart: ^0.27.7
  syntax_highlight: ^0.4.0
  dolumns: ^2.0.1
  url_router: ^0.2.1+3
  linked_scroll_controller: ^0.2.0
  performance: ^0.1.1
  highlight_text: ^1.7.0
  rive: ^0.13.8
  visibility_detector: ^0.4.0+2
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  yaml: ^3.1.2
  indent: ^2.0.0
  web: ^0.5.1

  # Signals
  signals_flutter: ^5.2.2
  context_watch_signals: ^2.0.0

  # MobX
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0+1
  context_watch_mobx: ^2.0.0

  # Beacon
  state_beacon: ^0.14.5
  context_watch_beacon: ^1.0.0-dev.2

  # Bloc
  flutter_bloc: ^8.1.2
  context_watch_bloc: ^2.0.0

  # GetX
  get: ^4.6.6
  context_watch_getx: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/showcase/
    - assets/svg/
    - lib/examples/showcase/variants/
    - lib/examples/animation_controller/variants/
    - lib/examples/rainbow/variants/
    - lib/examples/derived_state/variants/
    - lib/examples/counter/variants/
    - lib/examples/counter_with_propagation/variants/
    - lib/examples/nested_scopes/variants/
    - lib/examples/country_search/variants/
    - lib/examples/country_search/util/countries.json
    - pubspec.yaml
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode.ttf
