name: context_watch_base
description: "A common dependency for all context_watch-related packages"
version: 6.0.0
homepage: https://github.com/s0nerik/context_plus/tree/main/packages/context_watch
repository: https://github.com/s0nerik/context_plus/tree/main/packages/context_watch

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
