name: context_watch_mobx
description: "context_watch adapter for mobx package"
version: 1.0.1
homepage: https://github.com/s0nerik/context_plus/tree/main/packages/context_watch
repository: https://github.com/s0nerik/context_plus/tree/main/packages/context_watch
topics:
  - context-watch
  - mobx
  - integration
  - reactive
  - state-management

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  context_watch_base: ^2.0.2
  mobx: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
