name: context_watch_beacon
description: "context_watch adapter for state_beacon package"
version: 1.0.0-dev.2
homepage: https://github.com/s0nerik/context_watch
repository: https://github.com/s0nerik/context_watch
publish_to: "none" # Beacon implements ValueListenable, so there's no need in this package at the moment

environment:
    sdk: ">=3.0.6 <4.0.0"
    flutter: ">=3.17.0-1.0.pre.38"

dependencies:
    flutter:
        sdk: flutter
    context_watch_base: ^3.1.2
    state_beacon: ^0.14.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
