name: context_watch_getx
description: "context_watch adapter for 'get' package"
version: 5.0.3
homepage: https://github.com/s0nerik/context_plus/tree/main/packages/context_watch
repository: https://github.com/s0nerik/context_plus/tree/main/packages/context_watch
topics:
  - context-watch
  - get
  - integration
  - reactive
  - state-management

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  context_watch_base: ^8.0.3
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: {}
