name: context_watch_signals
description: "context_watch adapter for signals package"
version: 1.0.0-dev.1
homepage: https://github.com/s0nerik/context_watch
repository: https://github.com/s0nerik/context_watch

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  context_watch_base: ^1.0.0-dev.1
  signals: ^1.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
