name: context_watch
description: A hassle-free way to watch for observable value changes within the `build` method.
version: 5.1.0
homepage: https://github.com/s0nerik/context_plus/tree/main/packages/context_watch
repository: https://github.com/s0nerik/context_plus/tree/main/packages/context_watch
topics:
  - reactive
  - ui
  - state-management
  - extension

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  async_listenable: ^1.0.1
  meta: ^1.9.1
  context_watch_base: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  rxdart: ">=0.26.0 <0.29.0"

flutter:
