name: context_plus
description: Convenient value propagation and observing for Flutter
version: 2.2.1
homepage: https://github.com/s0nerik/context_plus/tree/main/packages/context_plus
repository: https://github.com/s0nerik/context_plus/tree/main/packages/context_plus
topics:
  - reactive
  - ui
  - state-management
  - extension

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  context_ref: ^1.3.0
  context_watch: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
